# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af3cd46d83dcd676bb1ba6e8aaae5364806df0ae1c897d9d2ff280709c539d5f6daa58635bc77fedb45b0855adefc4759f5845b7d3ac07a14a6bd92e517b789e

test:
  secret_key_base: 20fdc3a387021fcd8d80ed91190fc56162b452630d179f5e23b648d917001a7f8a4e86eda2fefa3103997d018d9b131d783861685587f30ab4cc029b001650c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
